checks:
    php:
        code_rating: true
        uppercase_constants: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        optional_parameters_at_the_end: true
        no_short_method_names:
            minimum: '3'
        no_short_variable_names:
            minimum: '3'
        return_doc_comments: true
        no_goto: true
        more_specific_types_in_doc_comments: true
        function_in_camel_caps: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_todo_comments: true
        avoid_perl_style_comments: true
        avoid_fixme_comments: true
        align_assignments: true
        avoid_multiple_statements_on_same_line: true
        return_doc_comment_if_not_inferrable: true
        simplify_boolean_return: true
        use_self_instead_of_fqcn: true
        param_doc_comment_if_not_inferrable: true
        naming_conventions:
            local_variable: '^[a-z][a-zA-Z0-9]*$'
            abstract_class_name: ^Abstract|Factory$
            utility_class_name: 'Utils?$'
            constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
            property_name: '^[a-z][a-zA-Z0-9]*$'
            method_name: '^(?:[a-z]|__)[a-zA-Z0-9]*$'
            parameter_name: '^[a-z][a-zA-Z0-9]*$'
            interface_name: '^[A-Z][a-zA-Z0-9]*Interface$'
            type_name: '^[A-Z][a-zA-Z0-9]*$'
            exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
            isser_method_name: '^(?:is|has|should|may|supports)'
        one_class_per_file: false
        side_effects_or_types: false
filter:
    excluded_paths: [test/*]
tools:
    external_code_coverage: true