notifications:
  email:
    on_success: never 
    on_failure: never 

language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  
before_script:
  - echo Start travis
  - echo Current dir is `pwd`
  - echo Home dir is `echo ~`
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs -i
  - phpcs --standard=PEAR /home/travis/build/thulin82/innebandybokning
  - phpcs --standard=Zend /home/travis/build/thulin82/innebandybokning