notifications:
  email:
    on_success: never 
    on_failure: never 

language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: 7.0  
  
before_script:
  - echo Start travis
  - echo Current dir is `pwd`
  - echo Home dir is `echo ~`
  - wget https://scrutinizer-ci.com/ocular.phar
  - cd ..
  - git clone git://github.com/squizlabs/PHP_CodeSniffer.git
  - php PHP_CodeSniffer/scripts/phpcs -h
  - php PHP_CodeSniffer/scripts/phpcbf -h
  - phpenv rehash

script:
  - php PHP_CodeSniffer/scripts/phpcs -i
  - php PHP_CodeSniffer/scripts/phpcs --standard=PEAR /home/travis/build/thulin82/innebandybokning
  - cd innebandybokning
  - phpunit
  
after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover